Ss/news feed
CS130-W20/team-B6 pull request #44
Opened 2020-02-20 22:57 UTC by samarseth

Added news feed stories and basic story structure right now.

PS: The top bar will be removed in the future and story buttons need to be restructured to match the format of the UI design that was presented in the proposal of the project.

2020-02-20 23:25 UTC, pacbac requested changes
Can you add some screenshots and also fix the merge conflicts?

2020-02-21 02:12 UTC, rishabhjain1198 commented
We would also want the image in the rectangles in the stories bar to be stretched out to fit.

2020-02-21 02:13 UTC, rishabhjain1198 commented on frontend/ios/Runner.xcodeproj/project.pbxproj
>  		3B3967161E833CAA004F5970 /* AppFrameworkInfo.plist in Resources */ = {isa = PBXBuildFile; fileRef = 3B3967151E833CAA004F5970 /* AppFrameworkInfo.plist */; };
What does this file do?

2020-02-21 02:14 UTC, rishabhjain1198 commented
I'm pretty sure a lot of Xcode project/runner files from frontend/ios should be removed from this PR.

2020-02-21 02:17 UTC, goelshashwat commented
@rishabhjain1198 I think stretching the logo in the news stories' button won't look good. It will distort the logo. According to me, what @samarseth did looks good.

2020-02-21 02:44 UTC, rishabhjain1198 commented
> @rishabhjain1198 I think stretching the logo in the news stories' button won't look good. It will distort the logo. According to me, what @samarseth did looks good.

Fair enough.

2020-02-21 20:06 UTC, samarseth commented
> I'm pretty sure a lot of Xcode project/runner files from frontend/ios should be removed from this PR.

Oh I assumed all the files that were supposed to be changed were already in the git ignore. Shouldn't make a dif

2020-02-21 22:12 UTC, pacbac approved these changes

2020-02-21 22:12 UTC, merged